export const servicios = [
  {
    id: 1,
    nombre: 'Consulta General',
    descripcion: 'Consulta médica para diagnóstico y tratamiento de diversas condiciones de salud. Ofrecemos servicios de atención integral para mantener y mejorar tu salud. Nuestros médicos altamente calificados están comprometidos con brindar cuidado personalizado a cada paciente.',
    urlImg: 'https://www.ucinmedica.com/wp-content/uploads/2020/07/consulta-medica.jpg',
    horasAtencion: '9:00 AM - 5:00 PM',
    diasAtencion: 'Lunes a Viernes',
    requisitos: 'Cita previa',
    doctores: ['Dr. Pérez', 'Dra. Rodríguez'],
    costo: '$50 - $100',
    duracion: '30 minutos',
    ubicacion: 'Calle Principal #123',
  },
  {
    id: 2,
    nombre: 'Cardiología',
    descripcion: 'Evaluación y tratamiento de enfermedades del corazón y sistema cardiovascular. Nuestro equipo de cardiólogos utiliza tecnología avanzada para realizar estudios precisos y ofrecer opciones de tratamiento efectivas. Tu salud cardíaca está en buenas manos.',
    urlImg: 'https://medicalcenter.bo/wp-content/uploads/2021/06/CARDIOLOGI%CC%81A.png',
    horasAtencion: '8:00 AM - 4:00 PM',
    diasAtencion: 'Martes y Jueves',
    requisitos: 'Ecocardiograma reciente',
    doctores: ['Dr. Gómez', 'Dra. Martínez'],
    costo: '$80 - $120',
    duracion: '45 minutos',
    ubicacion: 'Avenida Cardiaca #456',
  },
  {
    id: 3,
    nombre: 'Dermatología',
    descripcion: 'Diagnóstico y tratamiento de enfermedades de la piel, cabello y uñas. Nuestros dermatólogos expertos se especializan en ofrecer soluciones efectivas para diversas afecciones cutáneas. La salud de tu piel es nuestra prioridad.',
    urlImg: 'https://images.ecestaticos.com/6GjFfLqEM2t9my6xt-l_E1qX82I=/124x34:1920x1381/1200x900/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F76d%2Fddc%2Fd46%2F76dddcd46057c4a3ece9efa6e3d9c438.jpg',
    horasAtencion: '10:00 AM - 6:00 PM',
    diasAtencion: 'Miércoles y Viernes',
    requisitos: 'Historial dermatológico',
    doctores: ['Dra. Sánchez', 'Dr. Fernández'],
    costo: '$60 - $90',
    duracion: '40 minutos',
    ubicacion: 'Calle Dermis #789',
  },
  {
    id: 4,
    nombre: 'Ginecología',
    descripcion: 'Atención especializada en la salud de la mujer, incluyendo exámenes y cuidado prenatal. Nuestro equipo de ginecólogos brinda atención compasiva y personalizada a cada paciente. Nos preocupamos por tu bienestar integral.',
    urlImg: 'https://www.mgc.es/wp-content/uploads/2020/05/ecografia2.jpg',
    horasAtencion: '8:30 AM - 3:30 PM',
    diasAtencion: 'Lunes y Jueves',
    requisitos: 'Cita ginecológica',
    doctores: ['Dra. Gutiérrez', 'Dr. Jiménez'],
    costo: '$70 - $110',
    duracion: '35 minutos',
    ubicacion: 'Avenida Maternidad #567',
  },
  {
    id: 5,
    nombre: 'Pediatría',
    descripcion: 'Cuidado de la salud de niños y adolescentes, incluyendo chequeos regulares y vacunaciones. Nuestros pediatras están dedicados a proporcionar atención integral a los más pequeños. Tu hijo está en buenas manos con nosotros.',
    urlImg: 'https://centromedicoabc.com/wp-content/uploads/2022/12/pediatria.jpg',
    horasAtencion: '9:30 AM - 4:30 PM',
    diasAtencion: 'Martes y Viernes',
    requisitos: 'Registro de vacunación',
    doctores: ['Dra. López', 'Dr. Ramírez'],
    costo: '$55 - $95',
    duracion: '25 minutos',
    ubicacion: 'Calle de los Niños #234',
  },
  {
    id: 6,
    nombre: 'Oftalmología',
    descripcion: 'Diagnóstico y tratamiento de enfermedades oculares, exámenes de la vista y prescripción de lentes. Nuestros oftalmólogos utilizan tecnología avanzada para cuidar de tu salud visual. Tu vista es nuestra prioridad.',
    urlImg: 'https://aio-oftalmologia.com/wp-content/uploads/De-que-se-ocupa-un-oftalmologo.jpg',
    horasAtencion: '10:30 AM - 5:30 PM',
    diasAtencion: 'Miércoles y Sábado',
    requisitos: 'Cita oftalmológica',
    doctores: ['Dr. Vargas', 'Dra. Torres'],
    costo: '$75 - $115',
    duracion: '50 minutos',
    ubicacion: 'Avenida de la Visión #890',
  },
  {
    id: 7,
    nombre: 'Ortopedia',
    descripcion: 'Especialidad en el tratamiento de lesiones y enfermedades del sistema musculoesquelético. Nuestros ortopedistas ofrecen soluciones efectivas para mejorar la movilidad y calidad de vida. Recupera tu bienestar con nuestro equipo especializado.',
    urlImg: 'https://centromedicoabc.com/wp-content/uploads/2023/01/ortopedia.jpg',
    horasAtencion: '8:30 AM - 4:30 PM',
    diasAtencion: 'Lunes y Jueves',
    requisitos: 'Radiografías recientes',
    doctores: ['Dr. Hernández', 'Dra. Mendoza'],
    costo: '$90 - $130',
    duracion: '60 minutos',
    ubicacion: 'Calle de los Huesos #345',
  },
  {
    id: 8,
    nombre: 'Psicología',
    descripcion: 'Apoyo emocional y tratamiento de trastornos mentales y emocionales. Nuestros psicólogos brindan orientación y apoyo para superar desafíos emocionales. Tu bienestar mental es importante para nosotros.',
    urlImg: 'https://d226j30kfvtaz7.cloudfront.net/img/article/que-es-y-por-que-es-importante-la-psicologia-del-desarrollo.webp',
    horasAtencion: '11:00 AM - 6:00 PM',
    diasAtencion: 'Martes y Viernes',
    requisitos: 'Cita psicológica',
    doctores: ['Lic. Martínez', 'Psic. Soto'],
    costo: '$65 - $105',
    duracion: '45 minutos',
    ubicacion: 'Calle de la Mente #678',
  },
  {
    id: 9,
    nombre: 'Nutrición',
    descripcion: 'Asesoramiento y planificación de dietas para la salud y el bienestar. Nuestros nutricionistas te ayudarán a adoptar hábitos alimenticios saludables. Logra tus objetivos de salud con nuestro apoyo.',
    urlImg: 'https://alpina.com/media/mageplaza/blog/post/c/o/conocer-que-es-nutricion-es-fundamental-para-una-buena-salud.jpg',
    horasAtencion: '9:00 AM - 3:00 PM',
    diasAtencion: 'Miércoles y Sábado',
    requisitos: 'Registro alimenticio',
    doctores: ['Nutr. Pérez', 'Nutr. González'],
    costo: '$55 - $95',
    duracion: '30 minutos',
    ubicacion: 'Calle de los Nutrientes #901',
  },
  {
    id: 10,
    nombre: 'Endocrinología',
    descripcion: 'Diagnóstico y tratamiento de trastornos hormonales y metabólicos. Nuestros endocrinólogos ofrecen soluciones para equilibrar tu salud hormonal. Recupera tu vitalidad y bienestar con nuestro tratamiento especializado.',
    urlImg: 'https://www.endoriente.com/fotossubsecciones/macro_subseccion2017_07_05_16_56_01_13.jpg',
    horasAtencion: '10:00 AM - 5:00 PM',
    diasAtencion: 'Lunes y Jueves',
    requisitos: 'Análisis hormonales recientes',
    doctores: ['Dr. Ramírez', 'Dra. Gómez'],
    costo: '$85 - $125',
    duracion: '55 minutos',
    ubicacion: 'Avenida de las Hormonas #1234',
  },
  {
    id: 11,
    nombre: 'Odontología',
    descripcion: 'Cuidado dental que incluye limpiezas, extracciones y tratamientos de caries. Nuestros odontólogos se preocupan por tu salud dental y te brindan atención de calidad. Logra una sonrisa saludable con nosotros.',
    urlImg: 'https://bfesteticadental.com/wp-content/uploads/2017/06/Odontologia-Caracas-Venezuela-BF-Estetica-Dental-1024x682.jpg',
    horasAtencion: '8:30 AM - 4:30 PM',
    diasAtencion: 'Martes y Viernes',
    requisitos: 'Historial dental',
    doctores: ['Dr. Mora', 'Dra. Castillo'],
    costo: '$75 - $115',
    duracion: '50 minutos',
    ubicacion: 'Calle de los Dientes #5678',
  },
  {
    id: 12,
    nombre: 'Reumatología',
    descripcion: 'Diagnóstico y tratamiento de enfermedades del sistema musculoesquelético y tejidos conectivos. Nuestros reumatólogos se especializan en ofrecer soluciones para mejorar tu movilidad y calidad de vida. Recupera tu bienestar con nuestro equipo especializado.',
    urlImg: 'https://www.emergency-live.com/wp-content/uploads/2023/01/reumatologia-Esami-reumatologici-articolazioni-1-750x430.jpeg',
    horasAtencion: '11:00 AM - 5:00 PM',
    diasAtencion: 'Miércoles y Sábado',
    requisitos: 'Pruebas de laboratorio recientes',
    doctores: ['Dra. González', 'Dr. Sánchez'],
    costo: '$90 - $130',
    duracion: '60 minutos',
    ubicacion: 'Calle de las Articulaciones #7890',
  },
];